name: Publish Rust Crate

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        container:
            image: rust:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install cmake
              run: apt-get update && apt-get install -y cmake

            - name: Publish crate
              run: cargo publish
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
